### ISSUE TITLE
Crash on API 22 (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [ZsomborRajki/ordinal_formatter#1]
Hi @ZsomborRajki, thanks for this library first of all. It works flawlessly on the later Android versions, but in my testing with `API 22` (Android 5.1.1) I got the following error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/icu/text/MessageFormat;
	at com.example.ordinal_formatter.OrdinalFormatterPlugin.format(OrdinalFormatterPlugin.kt:55)
	at com.example.ordinal_formatter.OrdinalFormatterPlugin.onMethodCall(OrdinalFormatterPlugin.kt:44)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.icu.text.MessageFormat" on path: DexPathList[[zip file "/data/app/com.emberbaby.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.emberbaby.dev-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at com.example.ordinal_formatter.OrdinalFormatterPlugin.format(OrdinalFormatterPlugin.kt:55) 
	at com.example.ordinal_formatter.OrdinalFormatterPlugin.onMethodCall(OrdinalFormatterPlugin.kt:44) 
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258) 
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295) 
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322) 
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass) 
	at android.os.Handler.handleCallback(Handler.java:739) 
	at android.os.Handler.dispatchMessage(Handler.java:95) 
	at android.os.Looper.loop(Looper.java:145) 
	at android.app.ActivityThread.main(ActivityThread.java:6912) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at java.lang.reflect.Method.invoke(Method.java:372) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
	Suppressed: java.lang.ClassNotFoundException: android.icu.text.MessageFormat
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 15 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

Is this a known issue? Or do you have a workaround to fix it?

**Comment by ZsomborRajki** [comment]
Hi 
@shubhamsinghshubham777
MessageFormat API was added in API level 24. So the crash is valid. I will take a look and try to support older versions as well. 

Thanks for the report!

**Comment by ZsomborRajki** [comment]
closing this I found no feasible solution for older android versions. importing a java lib seems to be overkill. but I am open if someone opens an MR fixing this.

meanwhile bumping the minimum version on android to 24
